# build and deploy to GitHub Pages
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
    
      - name: Check if GCC available
        run: gcc --version

      - name: Build with make
        run: make build
    

      - name: Clean up
        run: make clean
