name: Build and deploy to production

on:
  push:
    branches:
      - main

jobs:
  deployment-prod:
    environment:
      name: prod
      url: https://cppbuild-prod.com
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Check if GCC available
        run: gcc --version

      - name: Build with make
        run: make

      - name: Clean up
        run: make clean
    